### ISSUE TITLE
Operating System

### ISSUE THREAD

**Issue by ihanwen99** [ShixianGuo/LeetCode#43]

**Comment by ihanwen99** [comment]
Hi, all.

不知道大家是不是都是C/C++小组的，我有一个关于我们训练的提议。

之前我有一个同学说我们可以尝试写一个OS，我觉得正好借这个机会我们可以组织一个教学/集体学习（哈哈当然我是学生啦）。

我在Github上面找到一个仓库，英文和翻译成中文的版本都有，分享给大家。也想听听大家的建议和指导，感谢！

https://github.com/cfenollosa/os-tutorial
https://github.com/ruiers/os-tutorial-cn

**Comment by ylink-lfs** [comment]
Done
